# Generated by Django 4.2.2 on 2024-02-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
