# Generated by Django 4.2.2 on 2024-02-28 14:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auther_desc',
            field=tinymce.models.HTMLField(default=None),
            preserve_default=False,
        ),
    ]
